import { ToastContainer } from 'react-toastify';
import './globals.css';
import { Providers } from './providers';
import ReduxProvider from '@/redux/ReduxProvider';

export const metadata = {
  title: 'Medi Sphere',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ReduxProvider>
          <Providers>{children}</Providers>
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
