import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import Navbar from '@/components/shared/Navbar';

export const metadata: Metadata = {
  title: 'Medi Sphere',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Navbar />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
